# Generated by Django 3.2.6 on 2021-08-22 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField()),
                ('image', models.URLField()),
                ('sqft', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpoints.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpoints.city')),
            ],
        ),
    ]
