# Generated by Django 3.2.6 on 2021-08-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.SlugField(max_length=128)),
                ('avatar', models.URLField()),
                ('rating', models.PositiveIntegerField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='city',
            name='zip',
            field=models.PositiveIntegerField(max_length=7),
        ),
        migrations.AlterField(
            model_name='property',
            name='sqft',
            field=models.PositiveIntegerField(max_length=4),
        ),
    ]
