# Generated by Django 3.2.6 on 2021-08-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0004_auto_20210822_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='feedback',
            field=models.CharField(max_length=128),
        ),
    ]
