# Generated by Django 3.2.6 on 2021-08-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0005_alter_review_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='baths',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='beds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
