# Generated by Django 3.2.6 on 2021-08-22 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0006_auto_20210822_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='propertytype',
            old_name='name',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='name',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='transation',
            old_name='name',
            new_name='slug',
        ),
    ]
